### PR TITLE
Shunt Battery Balancer V0.1

### PR DESCRIPTION
**Pull request by cgreenbaum**

### CODE REVIEW

**Comment by aaronbeekay** [comment]
@cgreenbaum Looks good, here's what you need:

* [ ] Schematic and board PDFs 
* [ ] BOM
* [ ] Board should have silkscreen and mounting holes

more to come

**Comment by aaronbeekay** [comment]
@cgreenbaum Good progress. Few more things before this can get merged:

## Standards
* You're missing title block information in your schematic.
* Gerbers should be in a "Gerbers" folder
* Your parts haven't been merged into Component-libraries -- you need to submit a pull request against Component-libraries for the parts you added
* Files are not at the top level of the repo (you do not have to fix this now but it's not the way the other repos are)

## Board
* Silkscreen text should be on layers 21 and 22 (tPlace and bPlace), not 121/122

Otherwise looks good.

The standards stuff sounds nit-picky, but I'm planning to develop tools that automatically check PRs for compliance with the design standards, as well as other automated tools for building and working with documentation. When those come around, it will make life a lot easier to have things named correctly.

**Comment by cgreenbaum** [comment]
@aaronbeekay Seems like the silkscreens should go on the tSilk and bSilk layers, but I'll move them if that's the way things work.

Which files need to be at the top of the repo?
*The .sch and .brd files with Gerbers in a folder.
*Is it okay to have a folder for documentation and datasheets?

Sorry, I thought I submitted a pull request for my component library.

**Comment by aaronbeekay** [comment]
@cgreenbaum I would be open to modifying the team CAM files so that 121/122 are valid silkscreen layers, but in the past everything has gone on 21/22, and the CAM files don't look for silk on 121/122.

Normally repos are put together with one board <=> one repository. In that arrangement, the .sch, .brd, and PDFs are at the top level. I have made "Documentation" folders for BOMs, etc., and I think that's a fine idea. For now I would not worry too much about it, since there is not an explicitly defined standard. Just giving you a heads-up that there may be a tighter standard in the future once we move into a glorious automated future.

**Comment by aaronbeekay** [comment]
Also -- the "Gerbers" folder (which, honestly, might be better named "CAM"...) should only have the ".GTO", ".GBL", etc., files, not the .sch and .brd.

**Comment by cgreenbaum** [comment]
No problem. I am encourage strict standards. It's the only way to manage a team, especially a team with as much membership turnover as a student project team. I'll get all this stuff fixed up by tonight.

**Comment by cgreenbaum** [comment]
@aaronbeekay: I think everything's in order now.

**Comment by aaronbeekay** [comment]
@cgreenbaum Looks good. You're OK to submit your manufacturing order request now.

**Pull request merged**
